class Quotes {
  static const List<String> dailyQuotes = [
    "The only bad workout is the one that didn't happen.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "It never gets easier, you just get stronger.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don't have to be extreme, just consistent.",
    "Sweat is just fat crying.",
    "Success starts with self-discipline.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "A one-hour workout is 4% of your day. No excuses.",
    "Sore today, strong tomorrow.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never came from comfort zones.",
    "Doubt kills more dreams than failure ever will.",
    "Fall in love with taking care of your body.",
    "Make your body the sexiest outfit you own.",
    "Strive for progress, not perfection.",
    "No matter how slow you go, you are still lapping everybody on the couch.",
    "Excuses don't burn calories.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "What seems impossible today will one day become your warm-up.",
    "Your health is an investment, not an expense.",
    "Take care of your body. It's the only place you have to live.",
    "Do something today that your future self will thank you for.",
    "The hardest lift of all is lifting your butt off the couch.",
    "Look in the mirror. That's your competition.",
    "Success isn't always about greatness. It's about consistency.",
    "Train insane or remain the same.",
    "If it doesn't challenge you, it doesn't change you.",
    "Don't limit your challenges, challenge your limits.",
    "Every day is another chance to get stronger.",
    "Clear your mind of can't.",
    "To achieve something you’ve never had, you must do something you’ve never done.",
    "Action is the foundational key to all success.",
    "Don't wish for a good body, work for it.",
    "Small steps every day.",
    "When you feel like quitting, think about why you started.",
    "Focus on your health, not your weight.",
    "Stop doubting yourself, work hard, and make it happen.",
    "You are far too smart to be the only thing standing in your way.",
    "Rome wasn't built in a day, but they worked on it every single day.",
    "Get fit in the gym, lose weight in the kitchen.",
    "Less sugar, more fruit. Less meat, more veggies. Less soda, more water. Less worry, more sleep.",
    "A year from now you may wish you had started today.",
    "You earn your trophies at practice. You just pick them up at competitions.",
    "Rest a while and run a mile.",
    "Obstacles are those frightful things you see when you take your eyes off your goal.",
    "Fitness is not about being better than someone else... It's about being better than you used to be.",
    "I will beat her. I will train harder. I will eat cleaner. I know her strengths. I've lost to her before but not this time. She is going down. I have the advantage because I know her well. She is the old me.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Pain is temporary. Quitting lasts forever.",
    "The difference between the impossible and the possible lies in a person's determination.",
    "I hate every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "I already know what giving up feels like. I want to see what happens if I don't.",
    "Blood, sweat and respect. First two you give, last one you earn.",
    "Things work out best for those who make the best of how things work out.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Just believe in yourself. Even if you don't, pretend that you do and, at some point, you will.",
    "You miss 100% of the shots you don't take.",
    "Whether you think you can or you think you can't, you're right.",
    "I have failed over and over and over again in my life. And that is why I succeed.",
    "It is not the mountain we conquer but ourselves.",
    "He who is not courageous enough to take risks will accomplish nothing in life.",
    "You must expect great things of yourself before you can do them.",
    "You are never too old to set another goal or to dream a new dream.",
    "To uncover your true potential you must first find your own limits and then you have to have the courage to blow past them.",
    "Don't wait until you've reached your goal to be proud of yourself. Be proud of every step you take toward reaching that goal.",
    "We do not stop playing because we grow old, we grow old because we stop playing.",
    "The body achieves what the mind believes.",
    "Hard work beats talent when talent doesn't work hard.",
    "There are no shortcuts to any place worth going.",
    "I find that the harder I work, the more luck I seem to have.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "You don't have to be great to start, but you have to start to be great.",
    "Only those who dare to fail greatly can ever achieve greatly.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Believe you can and you're halfway there.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "Don't let yesterday take up too much of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Limit your 'always' and your 'nevers'.",
    "Nothing is impossible. The word itself says 'I'm possible!'",
    "You are never too old to set another goal or to dream a new dream.",
    "Try to be a rainbow in someone's cloud.",
    "You do not find the happy life. You make it.",
    "Inspiration comes from within yourself. One has to be positive. When you're positive, good things happen.",
    "Sometimes you will never know the value of a moment, until it becomes a memory.",
    "The most wasted of days is one without laughter.",
    "You must do the things you think you cannot do.",
    "It isn't where you came from. It's where you're going that counts.",
    "It is never too late to be what you might have been.",
    "Stay close to anything that makes you glad you are alive.",
    "Some people look for a beautiful place. Others make a place beautiful.",
    "Happiness often sneaks in through a door you didn't know you left open.",
    "Happiness is not by chance, but by choice.",
    "Life changes very quickly, in a very positive way, if you let it.",
    "Keep your face to the sunshine and you cannot see a shadow.",
    "Never limit yourself because of others' limited imagination; never limit others because of your own limited imagination."
  ];
}
